CONDA_BUILD_SYSROOT: /Applications/Xcode_16.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
build_platform: osx-64
c_stdlib: macosx_deployment_target
c_stdlib_version: '11.0'
channel_sources: conda-forge
channel_targets: conda-forge main
cxx_compiler: clangxx
cxx_compiler_version: '19'
libmamba: 2.4.0 h7516003_1
openssl: '3.5'
pybind11: 3
pybind11_abi: 11
python: 3.12.* *_cpython
spdlog: '1.16'
target_platform: osx-arm64
zstd: '1.5'
