CONDA_BUILD_SYSROOT: /Applications/Xcode_16.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
MACOSX_DEPLOYMENT_TARGET: '10.13'
c_compiler: clang
c_compiler_version: '19'
c_stdlib: macosx_deployment_target
c_stdlib_version: '10.13'
channel_sources: conda-forge
channel_targets: conda-forge main
target_platform: noarch
